#!/usr/bin/env python3
"""
Generate C++ API documentation from Doxygen XML

This script generates Markdown documentation for NeuG C++ API classes.
It automatically cleans previously generated files before creating new ones.

Usage:
    python generate_cpp_docs.py                # Generate docs (with cleanup)
    python generate_cpp_docs.py --clean-only   # Only clean generated files
    python generate_cpp_docs.py --no-clean     # Generate without cleanup

Generated files:
    - {namespace}.md files for each namespace
    - index.md, index.rst
    - _meta.ts for Nextra navigation

Note: Only files generated by this script are cleaned/removed.
      Manual files are preserved.
"""

import os
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, List, Set, Any
import re
import argparse
import glob

SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent.parent
OUTPUT_DIR = SCRIPT_DIR.parent / "reference" / "cpp_api"
DOXYGEN_XML_PATH = SCRIPT_DIR.parent.parent / "build" / "html" / "reference" / "cpp_api_doxygen" / "xml"
KEY_CLASSES_CONFIG = SCRIPT_DIR / "cpp_key_classes.json"

def clean_generated_docs(output_dir: Path):
    """Remove only the files generated by this script."""
    print("🧹 Cleaning previously generated C++ API documentation...")
    
    if not output_dir.exists():
        print(f"📁 Output directory {output_dir} does not exist")
        return
    
    # Define generated file patterns
    generated_patterns = [
        "*.md",      # Namespace documentation files
        "index.rst", # Sphinx index
        "_meta.ts"   # Nextra navigation
    ]
    
    # Files to preserve (manually created)
    preserve_files = {
        "index.md",  # May be manually edited
    }
    
    cleaned_count = 0
    
    # Also clean reference-level _meta.ts
    reference_meta = output_dir.parent / "_meta.ts"
    if reference_meta.exists():
        try:
            reference_meta.unlink()
            print(f"  🗑️  Removed reference/_meta.ts")
            cleaned_count += 1
        except OSError as e:
            print(f"  ⚠️  Failed to remove reference/_meta.ts: {e}")
    
    for pattern in generated_patterns:
        matching_files = list(output_dir.glob(pattern))
        
        for file_path in matching_files:
            # Skip preserved files
            if file_path.name in preserve_files:
                print(f"  ℹ️   Preserving {file_path.name}")
                continue
            
            try:
                file_path.unlink()
                print(f"  🗑️  Removed {file_path.name}")
                cleaned_count += 1
            except OSError as e:
                print(f"  ⚠️  Failed to remove {file_path.name}: {e}")
    
    print(f"✅ Cleanup completed! Removed {cleaned_count} files.")

class CppAPIGenerator:
    """Generate C++ API documentation from Doxygen XML."""
    
    def __init__(self):
        self.namespaces = {}
        self.classes = {}
        self.key_classes_config = self._load_key_classes_config()
        self.target_namespaces = self.key_classes_config.get('target_namespaces', [
            'neug', 'gs', 'results', 'server'  # fallback default
        ])
    
    def _load_key_classes_config(self) -> Dict[str, Any]:
        """Load key classes configuration from JSON file."""
        try:
            if KEY_CLASSES_CONFIG.exists():
                import json
                with open(KEY_CLASSES_CONFIG, 'r', encoding='utf-8') as f:
                    config = json.load(f)
                    print(f"📋 Loaded {len(config.get('key_classes', []))} key classes from config")
                    print(f"📋 Target namespaces: {config.get('target_namespaces', [])}")
                    if 'documentation_categories' in config:
                        print(f"📋 Documentation categories: {list(config['documentation_categories'].keys())}")
                    if 'excluded_patterns' in config:
                        print(f"📋 Exclusion patterns: {len(config['excluded_patterns'])} patterns")
                    return config
            else:
                print(f"⚠️ Key classes config not found: {KEY_CLASSES_CONFIG}")
                return {"key_classes": [], "priority_display": True, "full_documentation": True}
        except Exception as e:
            print(f"❌ Error loading key classes config: {e}")
            return {"key_classes": [], "priority_display": True, "full_documentation": True}
    
    def _matches_excluded_pattern(self, class_name: str) -> bool:
        """Check if a class name matches any exclusion pattern."""
        excluded_patterns = self.key_classes_config.get('excluded_patterns', [])
        for pattern in excluded_patterns:
            if re.match(pattern, class_name):
                return True
        return False
    
    def _is_key_class(self, class_name: str) -> bool:
        """Check if a class is in the key classes list."""
        return class_name in self.key_classes_config.get('key_classes', [])
    
    def parse_doxygen_xml(self) -> bool:
        """Parse Doxygen XML files and extract API information."""
        if not DOXYGEN_XML_PATH.exists():
            print(f"❌ Doxygen XML path not found: {DOXYGEN_XML_PATH}")
            return False
        
        index_file = DOXYGEN_XML_PATH / "index.xml"
        if not index_file.exists():
            print(f"❌ Doxygen index.xml not found: {index_file}")
            return False
        
        print(f"🔍 Parsing Doxygen XML from: {DOXYGEN_XML_PATH}")
        
        # Parse index.xml to get compound list
        tree = ET.parse(index_file)
        root = tree.getroot()
        
        compounds = []
        for compound in root.findall('.//compound'):
            kind = compound.get('kind')
            refid = compound.get('refid')
            name = compound.find('name').text if compound.find('name') is not None else ''
            
            if kind in ['namespace', 'class', 'struct']:
                compounds.append({
                    'kind': kind,
                    'refid': refid,
                    'name': name,
                    'file': f"{refid}.xml"
                })
        
        print(f"📊 Found {len(compounds)} compounds")
        
        # Parse individual compound files
        for compound in compounds:
            self._parse_compound_file(compound)
        
        # Filter relevant namespaces and classes
        self._filter_target_api()
        
        print(f"🎯 Filtered to {len(self.namespaces)} namespaces and {len(self.classes)} classes")
        return True
    
    def _parse_compound_file(self, compound_info: Dict[str, str]):
        """Parse individual compound XML file."""
        xml_file = DOXYGEN_XML_PATH / compound_info['file']
        if not xml_file.exists():
            return
        
        try:
            tree = ET.parse(xml_file)
            root = tree.getroot()
            
            compound_def = root.find('.//compounddef')
            if compound_def is None:
                return
            
            kind = compound_def.get('kind')
            compound_name = compound_info['name']
            
            if kind == 'namespace':
                self._parse_namespace(compound_def, compound_name)
            elif kind in ['class', 'struct']:
                self._parse_class(compound_def, compound_name, kind)
                
        except ET.ParseError as e:
            print(f"⚠️ Failed to parse {xml_file}: {e}")
    
    def _parse_namespace(self, ns_def, ns_name: str):
        """Parse namespace definition."""
        self.namespaces[ns_name] = {
            'name': ns_name,
            'brief': self._extract_brief_description(ns_def),
            'detailed': self._extract_detailed_description(ns_def),
            'classes': [],
            'functions': []
        }
    
    def _parse_class(self, class_def, class_name: str, kind: str):
        """Parse class or struct definition."""
        self.classes[class_name] = {
            'name': class_name,
            'kind': kind,
            'brief': self._extract_brief_description(class_def),
            'detailed': self._extract_detailed_description(class_def),
            'methods': self._extract_methods(class_def),
            'members': self._extract_members(class_def),
            'namespace': self._extract_namespace(class_name),
            'since': self._extract_since_info(class_def)
        }
    
    def _extract_brief_description(self, element) -> str:
        """Extract brief description from XML element."""
        # For class-level descriptions, look for briefdescription directly under compounddef
        # (not nested within memberdef elements)
        for brief_elem in element.findall('briefdescription'):
            if brief_elem is not None:
                text = self._xml_to_text(brief_elem).strip()
                if text:  # Only return non-empty descriptions
                    # Filter out copyright information
                    text = self._filter_copyright_info(text)
                    if text:  # Check again after filtering
                        # Clean up multiple newlines in brief descriptions
                        text = re.sub(r'\n+', ' ', text)
                        # Apply automatic code formatting
                        text = self._format_text_with_code_detection(text)
                        return text
        return ""
    
    def _extract_detailed_description(self, element) -> str:
        """Extract detailed description from XML element, excluding special sections."""
        # For class-level descriptions, look for detaileddescription directly under compounddef
        # (not nested within memberdef elements)
        for detailed_elem in element.findall('detaileddescription'):
            if detailed_elem is not None:
                # Create a copy of the element to modify without affecting the original
                import xml.etree.ElementTree as ET
                detailed_copy = ET.fromstring(ET.tostring(detailed_elem))
                
                # Remove special sections that will be handled separately
                # We need to find and remove these elements safely
                def remove_elements_by_xpath(root, xpath):
                    """Remove elements matching xpath from root."""
                    elements_to_remove = []
                    for elem in root.iter():
                        if xpath == './/simplesect[@kind="return"]' and elem.tag == 'simplesect' and elem.get('kind') == 'return':
                            elements_to_remove.append((elem, self._find_parent(root, elem)))
                        elif xpath == './/simplesect[@kind="note"]' and elem.tag == 'simplesect' and elem.get('kind') == 'note':
                            elements_to_remove.append((elem, self._find_parent(root, elem)))
                        elif xpath == './/simplesect[@kind="since"]' and elem.tag == 'simplesect' and elem.get('kind') == 'since':
                            elements_to_remove.append((elem, self._find_parent(root, elem)))
                        elif xpath == './/parameterlist[@kind="exception"]' and elem.tag == 'parameterlist' and elem.get('kind') == 'exception':
                            elements_to_remove.append((elem, self._find_parent(root, elem)))
                        elif xpath == './/parameterlist[@kind="param"]' and elem.tag == 'parameterlist' and elem.get('kind') == 'param':
                            elements_to_remove.append((elem, self._find_parent(root, elem)))
                    
                    for elem, parent in elements_to_remove:
                        if parent is not None:
                            parent.remove(elem)
                
                sections_to_remove = [
                    './/simplesect[@kind="return"]',
                    './/simplesect[@kind="note"]',
                    './/simplesect[@kind="since"]',
                    './/parameterlist[@kind="exception"]',
                    './/parameterlist[@kind="param"]'
                ]
                
                for xpath in sections_to_remove:
                    remove_elements_by_xpath(detailed_copy, xpath)
                
                # Also remove @see sections (handled separately)
                for elem in list(detailed_copy.iter()):
                    if elem.tag == 'simplesect' and elem.get('kind') == 'see':
                        parent = self._find_parent(detailed_copy, elem)
                        if parent is not None:
                            parent.remove(elem)
                
                # Convert the cleaned XML to text
                text = self._xml_to_text(detailed_copy).strip()
                if text:  # Only return non-empty descriptions
                    # Filter out copyright information
                    text = self._filter_copyright_info(text)
                    if text:  # Check again after filtering
                        # Add paragraph breaks before bold headers (like **Usage Example:**)
                        # Match cases where there's no newline or just a single newline before bold headers
                        text = re.sub(r'([^\n])\n?(\*\*[A-Z][^*]+:\*\*)', r'\1\n\n\2', text)
                        
                        # Clean up excessive newlines but preserve paragraph structure
                        text = re.sub(r'\n{3,}', '\n\n', text)
                        text = re.sub(r'^\s*\n+', '', text)  # Remove leading empty lines
                        text = re.sub(r'\n+\s*$', '', text)  # Remove trailing empty lines
                        
                        # Apply automatic code formatting
                        text = self._format_text_with_code_detection(text)
                        return text
        return ""
    
    def _find_parent(self, root, target):
        """Find parent of target element in root."""
        for elem in root.iter():
            if target in elem:
                return elem
        return None
    
    def _filter_copyright_info(self, text: str) -> str:
        """Filter out copyright and license information from text."""
        if not text:
            return text
        
        # Split into lines for processing
        lines = text.split('\n')
        filtered_lines = []
        
        for line in lines:
            line_lower = line.lower().strip()
            
            # Skip lines that contain copyright/license information
            if any(keyword in line_lower for keyword in [
                'copyright', 'licensed under', 'license', 'apache', 'mit license',
                'alibaba group holding', 'kùzu project', 'github.com/kuzudb',
                'http://www.apache.org/licenses', 'without warranties',
                'distributed under the license', 'see the license',
                'this file is originally from', 'modified by', 'zhou xiaoli'
            ]):
                continue
            
            # Skip empty lines that result from filtering
            if line.strip():
                filtered_lines.append(line)
        
        # Join the filtered lines back
        result = '\n'.join(filtered_lines).strip()
        
        # If all content was filtered out, return empty string
        if not result or len(result.split()) < 3:  # Less than 3 words remaining
            return ""
        
        return result
    
    def _extract_methods(self, class_def) -> List[Dict[str, str]]:
        """Extract methods from class definition."""
        methods = []
        for member in class_def.findall('.//memberdef[@kind="function"]'):
            if member.get('prot') == 'public':  # Only public methods
                # Extract information in correct order (notes/return/exceptions before detailed description)
                notes = self._extract_notes(member)
                return_info = self._extract_return_info(member)
                exceptions = self._extract_exceptions_from_xml(member)
                since_info = self._extract_since_info(member)
                
                method_info = {
                    'name': self._get_element_text(member, 'name'),
                    'type': self._get_element_text(member, 'type'),
                    'argsstring': self._get_element_text(member, 'argsstring'),
                    'brief': self._extract_brief_description(member),
                    'detailed': self._extract_detailed_description(member),
                    'protection': member.get('prot', 'public'),
                    'params': self._extract_parameters(member),
                    'return': return_info,
                    'exceptions': exceptions,
                    'notes': notes,
                    'since': since_info
                }
                methods.append(method_info)
        return methods
    
    def _extract_exceptions(self, method_info: Dict[str, str]) -> List[Dict[str, str]]:
        """Extract exception information from method detailed description."""
        exceptions = []
        detailed_text = method_info.get('detailed', '')
        if not detailed_text:
            return exceptions
        
        # Split text into lines for easier processing
        lines = detailed_text.split('\n')
        current_exception = None
        
        for line in lines:
            line = line.strip()
            # Look for @throws patterns
            throws_match = re.match(r'@throws?\s+([a-zA-Z:_][a-zA-Z0-9:_]*)\s+(.*)', line)
            if throws_match:
                exc_type = throws_match.group(1)
                exc_desc = throws_match.group(2).strip()
                if current_exception:
                    exceptions.append(current_exception)
                current_exception = {
                    'type': exc_type,
                    'description': exc_desc
                }
            elif current_exception and line and not line.startswith('@'):
                # Continue previous exception description
                current_exception['description'] += ' ' + line
        
        # Add the last exception if any
        if current_exception:
            exceptions.append(current_exception)
        
        return exceptions
    
    def _extract_exceptions_from_xml(self, method_def) -> List[Dict[str, str]]:
        """Extract exception information directly from Doxygen XML."""
        exceptions = []
        
        # Look for parameterlist with kind="exception"
        exception_list = method_def.find('.//parameterlist[@kind="exception"]')
        if exception_list is not None:
            for param_item in exception_list.findall('parameteritem'):
                # Get exception type from parameternamelist
                name_list = param_item.find('parameternamelist')
                if name_list is not None:
                    param_name = name_list.find('parametername')
                    if param_name is not None and param_name.text:
                        exc_type = param_name.text.strip()
                        
                        # Get exception description
                        desc_elem = param_item.find('parameterdescription')
                        exc_desc = ""
                        if desc_elem is not None:
                            exc_desc = self._xml_to_text(desc_elem).strip()
                        
                        exceptions.append({
                            'type': exc_type,
                            'description': exc_desc
                        })
        
        return exceptions
    
    def _extract_parameters(self, method_def) -> List[Dict[str, str]]:
        """Extract parameter information from method definition."""
        params = []
        
        # First, extract basic parameter info from <param> tags
        param_info_map = {}
        for param in method_def.findall('.//param'):
            param_name = self._get_element_text(param, 'declname')
            param_info_map[param_name] = {
                'type': self._get_element_text(param, 'type'),
                'name': param_name,
                'brief': ''
            }
        
        # Then, extract parameter descriptions from <parameterlist kind="param">
        param_list = method_def.find('.//parameterlist[@kind="param"]')
        if param_list is not None:
            for param_item in param_list.findall('.//parameteritem'):
                param_name_elem = param_item.find('.//parametername')
                param_desc_elem = param_item.find('.//parameterdescription')
                
                if param_name_elem is not None and param_desc_elem is not None:
                    param_name = param_name_elem.text.strip() if param_name_elem.text else ''
                    param_desc = self._xml_to_text(param_desc_elem).strip()
                    
                    if param_name in param_info_map:
                        param_info_map[param_name]['brief'] = param_desc
        
        # Convert to list in the order they appear in the function signature
        for param_name in param_info_map:
            params.append(param_info_map[param_name])
        
        return params
    
    def _extract_return_info(self, method_def) -> Dict[str, str]:
        """Extract return type and description from Doxygen XML."""
        return_type = self._get_element_text(method_def, 'type')
        return_desc = ""
        
        # Look for explicit @return documentation in detaileddescription
        detailed_elem = method_def.find('.//detaileddescription')
        if detailed_elem is not None:
            # Look for simplesect with kind="return"
            return_section = detailed_elem.find('.//simplesect[@kind="return"]')
            if return_section is not None:
                return_desc = self._xml_to_text(return_section).strip()
                # Remove the "return:" prefix if present
                return_desc = re.sub(r'^returns?:?\s*', '', return_desc, flags=re.IGNORECASE)
        
        return {
            'type': return_type if return_type else "",
            'description': return_desc
        }
    
    def _extract_notes(self, method_def) -> List[str]:
        """Extract @note information from Doxygen XML."""
        notes = []
        
        detailed_elem = method_def.find('.//detaileddescription')
        if detailed_elem is not None:
            # Look for simplesect with kind="note"
            note_sections = detailed_elem.findall('.//simplesect[@kind="note"]')
            for note_section in note_sections:
                note_text = self._xml_to_text(note_section).strip()
                # Remove the "note:" prefix if present
                note_text = re.sub(r'^notes?:?\s*', '', note_text, flags=re.IGNORECASE)
                if note_text:
                    notes.append(note_text)
        
        return notes
    
    def _extract_since_info(self, element) -> str:
        """Extract @since information from Doxygen XML."""
        detailed_elem = element.find('.//detaileddescription')
        if detailed_elem is not None:
            since_sections = detailed_elem.findall('.//simplesect[@kind="since"]')
            for since_section in since_sections:
                since_text = self._xml_to_text(since_section).strip()
                if since_text:
                    # Clean up common prefixes and formatting
                    cleaned_since = re.sub(r'^since:\s*', '', since_text, flags=re.IGNORECASE)
                    return cleaned_since.strip()
        return ""
    
    def _extract_members(self, class_def) -> List[Dict[str, str]]:
        """Extract member variables from class definition."""
        members = []
        for member in class_def.findall('.//memberdef[@kind="variable"]'):
            if member.get('prot') == 'public':  # Only public members
                member_info = {
                    'name': self._get_element_text(member, 'name'),
                    'type': self._get_element_text(member, 'type'),
                    'brief': self._extract_brief_description(member)
                }
                members.append(member_info)
        return members
    
    def _extract_namespace(self, class_name: str) -> str:
        """Extract namespace from class name."""
        parts = class_name.split('::')
        if len(parts) > 1:
            return '::'.join(parts[:-1])
        return ""
    
    def _get_element_text(self, parent, tag_name: str) -> str:
        """Get text content of child element."""
        elem = parent.find(tag_name)
        return elem.text.strip() if elem is not None and elem.text else ""
    
    def _format_method_signature(self, method_name: str, args_string: str) -> str:
        """Format method signature with proper line breaks for long parameter lists."""
        if not args_string or len(args_string) <= 80:
            # Short signature - keep on one line
            return f"`{method_name}{args_string}`"
        
        # Long signature - format with line breaks
        # Remove outer parentheses
        args_content = args_string.strip('()')
        
        if not args_content:
            return f"`{method_name}()`"
        
        # Split parameters by comma, but be careful with nested templates
        params = []
        current_param = ""
        paren_depth = 0
        angle_depth = 0
        
        for char in args_content:
            if char == '(':
                paren_depth += 1
            elif char == ')':
                paren_depth -= 1
            elif char == '<':
                angle_depth += 1
            elif char == '>':
                angle_depth -= 1
            elif char == ',' and paren_depth == 0 and angle_depth == 0:
                params.append(current_param.strip())
                current_param = ""
                continue
            
            current_param += char
        
        # Add the last parameter
        if current_param.strip():
            params.append(current_param.strip())
        
        if len(params) <= 2:
            # Still manageable on one line
            return f"`{method_name}{args_string}`"
        
        # Format with line breaks - return as separate title and code block
        # Create a simplified title with ellipsis
        title_signature = f"`{method_name}(...)`"
        detailed_signature = f"```cpp\n{method_name}(\n" + \
                           "".join(f"    {param}" + ("," if i < len(params) - 1 else "") + "\n" 
                                  for i, param in enumerate(params)) + \
                           ")\n```"
        
        return {
            'title': title_signature,
            'signature': detailed_signature
        }
    
    def _extract_code_line_text(self, codeline_element) -> str:
        """Extract text content from a codeline element, preserving spaces."""
        text = ""
        if codeline_element.text:
            text += codeline_element.text
        
        for child in codeline_element:
            # Handle highlight elements (syntax highlighting from Doxygen)
            if child.tag == 'highlight':
                if child.text:
                    text += child.text
                for subchild in child:
                    # Handle <sp/> space elements inside highlight
                    if subchild.tag == 'sp':
                        text += " "
                    elif subchild.tag == 'ref':
                        if subchild.text:
                            text += subchild.text
                    elif subchild.text:
                        text += subchild.text
                    if subchild.tail:
                        text += subchild.tail
                if child.tail:
                    text += child.tail
            elif child.tag == 'sp':
                # Space element at codeline level
                text += " "
                if child.tail:
                    text += child.tail
            elif child.tag == 'ref':
                # Reference to other symbol
                if child.text:
                    text += child.text
                if child.tail:
                    text += child.tail
            else:
                if child.text:
                    text += child.text
                if child.tail:
                    text += child.tail
        
        return text
    
    def _format_text_with_code_detection(self, text: str) -> str:
        """Automatically detect and format code elements in text, skipping code blocks."""
        if not text:
            return text
        
        # Split text into code blocks and non-code parts
        # Code blocks are marked by ```...```
        parts = re.split(r'(```[\s\S]*?```)', text)
        
        # Only detect clearly identifiable code elements
        code_patterns = [
            r'\b(true|false|nullptr|void|const|static|virtual|override|int|char|bool|double|float|size_t)\b',  # C++ keywords and types
            r'\b(std::[a-zA-Z_][a-zA-Z0-9_]*)\b',  # std:: types like std::runtime_error
            r'\b[A-Z][a-zA-Z]*::[a-zA-Z_][a-zA-Z0-9_]*\b',  # Namespace::Class like gs::Connection
            r'\b[a-zA-Z_][a-zA-Z0-9_]*_\b',  # Variables ending with underscore (member variables)
        ]
        
        result_parts = []
        for part in parts:
            # Skip code blocks (they start with ```)
            if part.startswith('```'):
                result_parts.append(part)
            else:
                # Apply patterns only to non-code parts
                formatted_part = part
                for pattern in code_patterns:
                    # Don't add backticks if already inside backticks
                    formatted_part = re.sub(
                        r'(?<!`)' + pattern + r'(?!`)',
                        r'`\g<0>`',
                        formatted_part
                    )
                result_parts.append(formatted_part)
        
        return ''.join(result_parts)
    
    def _xml_to_text(self, element) -> str:
        """Convert XML element to properly formatted plain text."""
        if element is None:
            return ""
        
        # Handle different Doxygen XML elements
        if element.tag in ['detaileddescription', 'briefdescription']:
            # Description containers - don't strip whitespace (preserve code indentation)
            text = ""
            if element.text:
                text += element.text
            
            for child in element:
                text += self._xml_to_text(child)
                if child.tail:
                    text += child.tail
            
            return text
        
        elif element.tag == 'para':
            # Paragraph - should have line breaks around it
            text = ""
            if element.text:
                text += element.text
            
            for child in element:
                text += self._xml_to_text(child)
                if child.tail:
                    text += child.tail
            
            return text.strip() + "\n\n"
        
        elif element.tag in ['emphasis', 'bold']:
            # Emphasis and bold formatting
            text = ""
            if element.text:
                text += element.text
            
            for child in element:
                text += self._xml_to_text(child)
                if child.tail:
                    text += child.tail
            
            # Apply markdown formatting
            if element.tag == 'emphasis':
                return f"*{text}*"
            elif element.tag == 'bold':
                return f"**{text}**"
            return text
        
        elif element.tag == 'programlisting':
            # Code block - format as markdown code fence
            lines = []
            for child in element:
                if child.tag == 'codeline':
                    line_text = self._extract_code_line_text(child)
                    lines.append(line_text)
            code_content = '\n'.join(lines)
            return f"\n\n```cpp\n{code_content}\n```\n\n"
        
        elif element.tag == 'codeline':
            # Individual code line (handled by programlisting above)
            return self._extract_code_line_text(element)
        
        elif element.tag in ['computeroutput', 'code']:
            # Inline code formatting elements
            text = ""
            if element.text:
                text += element.text
            
            for child in element:
                text += self._xml_to_text(child)
                if child.tail:
                    text += child.tail
            
            return f"`{text}`"
        
        elif element.tag == 'ref':
            # References to other classes/functions
            if element.text:
                return f"`{element.text}`"
            return ""
        
        elif element.tag in ['itemizedlist', 'orderedlist']:
            # Lists
            text = "\n\n"
            item_count = 1
            for child in element:
                if child.tag == 'listitem':
                    item_text = self._xml_to_text(child).strip()
                    # Remove extra newlines from list items
                    item_text = re.sub(r'\n+', ' ', item_text)
                    
                    if element.tag == 'itemizedlist':
                        text += f"- {item_text}\n"
                    else:
                        text += f"{item_count}. {item_text}\n"
                        item_count += 1
            return text + "\n"
        
        elif element.tag == 'listitem':
            # List items
            text = ""
            for child in element:
                text += self._xml_to_text(child)
            return text.strip()
        
        else:
            # Generic handling for other elements
            text = ""
            if element.text:
                text += element.text
            
            for child in element:
                text += self._xml_to_text(child)
                if child.tail:
                    text += child.tail
            
            # Clean up whitespace but preserve intentional line breaks
            text = re.sub(r'[ \t]+', ' ', text)  # Normalize spaces and tabs
            text = re.sub(r'\n[ \t]+', '\n', text)  # Remove leading whitespace on lines
            text = re.sub(r'[ \t]+\n', '\n', text)  # Remove trailing whitespace on lines
            text = re.sub(r'\n{3,}', '\n\n', text)  # Limit consecutive newlines to 2
            
            return text.strip()
    
    def _filter_target_api(self):
        """Filter to only include target namespaces and their classes."""
        # Group classes by namespace
        for class_name, class_info in list(self.classes.items()):
            namespace = class_info['namespace']
            root_namespace = namespace.split('::')[0] if namespace else ''
            
            if root_namespace in self.target_namespaces:
                # Skip private implementation classes
                if self._is_private_class(class_name):
                    print(f"🚫 Skipping private class: {class_name}")
                    continue
                    
                # Add class to its namespace
                if namespace in self.namespaces:
                    self.namespaces[namespace]['classes'].append(class_info)
    
    def _has_documentation(self, method: Dict[str, Any]) -> bool:
        """Check if a method has any documentation."""
        if method.get('brief'):
            return True
        if method.get('detailed'):
            return True
        # Check if any parameters have descriptions
        for param in method.get('params', []):
            if param.get('brief'):
                return True
        # Check for return description
        return_info = method.get('return', {})
        if return_info and return_info.get('description'):
            return True
        return False
    
    def _add_detailed_class_docs(self, content: str, class_info: Dict[str, Any]) -> str:
        """Add detailed documentation for key classes using pure Markdown."""
        # Add class description
        if class_info.get('detailed'):
            content += f"{class_info['detailed']}\n\n"
        
        # Add class-level since information
        since_info = class_info.get('since', '')
        if since_info:
            content += f"- **Since:** {since_info}\n\n"
        
        # Add constructor and destructor information (only if documented)
        class_simple_name = class_info['name'].split('::')[-1]
        constructors = [m for m in class_info.get('methods', []) 
                       if m.get('name') == class_simple_name and self._has_documentation(m)]
        destructors = [m for m in class_info.get('methods', []) 
                      if m.get('name') == f'~{class_simple_name}' and self._has_documentation(m)]
        
        if constructors or destructors:
            content += "### Constructors & Destructors\n\n"
            
            # Add constructors first
            for ctor in constructors:
                method_name = ctor.get('name', '')
                args_string = ctor.get('argsstring', '')
                formatted_signature = self._format_method_signature(method_name, args_string)
                
                if isinstance(formatted_signature, dict):
                    # Long signature with separate title and code block
                    content += f"#### {formatted_signature['title']}\n\n"
                    content += f"{formatted_signature['signature']}\n\n"
                else:
                    # Short signature on one line
                    content += f"#### {formatted_signature}\n\n"
                if ctor.get('brief'):
                    content += f"{ctor['brief']}\n\n"
                if ctor.get('detailed'):
                    content += f"{ctor['detailed']}\n\n"
                
                # Add parameter documentation for constructors
                params = ctor.get('params', [])
                if params:
                    content += "- **Parameters:**\n"
                    for param in params:
                        param_name = param.get('name', '')
                        param_desc = param.get('brief', '')
                        if param_desc:
                            content += f"  - `{param_name}`: {param_desc}\n"
                        else:
                            content += f"  - `{param_name}`\n"
                    content += "\n"
                
                # Add notes, exceptions, returns for constructors
                notes = ctor.get('notes', [])
                if notes:
                    content += "- **Notes:**\n"
                    for note in notes:
                        formatted_note = self._format_text_with_code_detection(note)
                        content += f"  - {formatted_note}\n"
                    content += "\n"
                
                exceptions = ctor.get('exceptions', [])
                if exceptions:
                    content += "- **Throws:**\n"
                    for exc in exceptions:
                        exc_type = self._format_text_with_code_detection(exc.get('type', ''))
                        exc_desc = exc.get('description', '')
                        content += f"  - {exc_type}: {exc_desc}\n"
                    content += "\n"
                
                # Add since information
                since_info = ctor.get('since', '')
                if since_info:
                    content += f"- **Since:** {since_info}\n\n"
            
            # Add destructors
            for dtor in destructors:
                method_name = dtor.get('name', '')
                args_string = dtor.get('argsstring', '')
                formatted_signature = self._format_method_signature(method_name, args_string)
                
                if isinstance(formatted_signature, dict):
                    # Long signature with separate title and code block
                    content += f"#### {formatted_signature['title']}\n\n"
                    content += f"{formatted_signature['signature']}\n\n"
                else:
                    # Short signature on one line
                    content += f"#### {formatted_signature}\n\n"
                if dtor.get('brief'):
                    content += f"{dtor['brief']}\n\n"
                if dtor.get('detailed'):
                    content += f"{dtor['detailed']}\n\n"
                
                # Add notes, exceptions for destructors
                notes = dtor.get('notes', [])
                if notes:
                    content += "- **Notes:**\n"
                    for note in notes:
                        formatted_note = self._format_text_with_code_detection(note)
                        content += f"  - {formatted_note}\n"
                    content += "\n"
                
                exceptions = dtor.get('exceptions', [])
                if exceptions:
                    content += "- **Throws:**\n"
                    for exc in exceptions:
                        exc_type = self._format_text_with_code_detection(exc.get('type', ''))
                        exc_desc = exc.get('description', '')
                        content += f"  - {exc_type}: {exc_desc}\n"
                    content += "\n"
                
                # Add since information
                since_info = dtor.get('since', '')
                if since_info:
                    content += f"- **Since:** {since_info}\n\n"
        
        # Add public methods (excluding constructors and destructors)
        # Also skip methods without any documentation
        methods = [m for m in class_info.get('methods', []) if 
                   m.get('name') != class_simple_name and 
                   m.get('name') != f'~{class_simple_name}' and 
                   m.get('protection') == 'public' and
                   self._has_documentation(m)]
        if methods:
            content += "### Public Methods\n\n"
            for method in methods:
                method_name = method.get('name', 'Unknown')
                method_args = method.get('argsstring', '()')
                formatted_signature = self._format_method_signature(method_name, method_args)
                
                if isinstance(formatted_signature, dict):
                    # Long signature with separate title and code block
                    content += f"#### {formatted_signature['title']}\n\n"
                    content += f"{formatted_signature['signature']}\n\n"
                else:
                    # Short signature on one line
                    content += f"#### {formatted_signature}\n\n"
                
                if method.get('brief'):
                    content += f"{method['brief']}\n\n"
                
                if method.get('detailed'):
                    content += f"{method['detailed']}\n\n"
                
                # Add parameter documentation with bullet points
                params = method.get('params', [])
                if params:
                    content += "- **Parameters:**\n"
                    for param in params:
                        param_name = param.get('name', '')
                        param_desc = param.get('brief', '')
                        if param_desc:
                            content += f"  - `{param_name}`: {param_desc}\n"
                        else:
                            content += f"  - `{param_name}`\n"
                    content += "\n"
                
                # Add notes as bullet points
                notes = method.get('notes', [])
                if notes:
                    content += "- **Notes:**\n"
                    for note in notes:
                        formatted_note = self._format_text_with_code_detection(note)
                        content += f"  - {formatted_note}\n"
                    content += "\n"
                
                # Add exception information as bullet points
                exceptions = method.get('exceptions', [])
                if exceptions:
                    content += "- **Throws:**\n"
                    for exc in exceptions:
                        exc_type = self._format_text_with_code_detection(exc.get('type', ''))
                        exc_desc = exc.get('description', '')
                        content += f"  - {exc_type}: {exc_desc}\n"
                    content += "\n"
                
                # Add return information (simplified - just description)
                return_info = method.get('return', {})
                if return_info and return_info.get('description'):
                    formatted_desc = self._format_text_with_code_detection(return_info.get('description', ''))
                    content += f"- **Returns:** {formatted_desc}\n\n"
                
                # Add since information
                since_info = method.get('since', '')
                if since_info:
                    content += f"- **Since:** {since_info}\n\n"
        
        return content
    
    def _add_basic_class_docs(self, content: str, class_info: Dict[str, Any]) -> str:
        """Add basic documentation for non-key classes using pure Markdown."""
        # Add brief class description
        if class_info.get('detailed'):
            # Truncate detailed description for basic docs
            detailed = class_info['detailed'][:200] + "..." if len(class_info['detailed']) > 200 else class_info['detailed']
            content += f"{detailed}\n\n"
        
        # Add method overview
        methods = class_info.get('methods', [])
        if methods:
            content += "**Public Methods:**\n\n"
            for method in methods[:10]:  # Limit to first 10 methods for basic docs
                method_name = method.get('name', 'Unknown')
                method_args = method.get('argsstring', '()')
                method_brief = method.get('brief', '').split('.')[0] if method.get('brief') else ''
                
                # For basic docs, use simplified formatting (keep inline if not too long)
                if len(method_args) <= 60:
                    signature = f"`{method_name}{method_args}`"
                else:
                    # For very long signatures in basic docs, just truncate
                    truncated_args = method_args[:50] + "..." if len(method_args) > 50 else method_args
                    signature = f"`{method_name}{truncated_args}`"
                
                if method_brief:
                    content += f"- {signature} - {method_brief}\n"
                else:
                    content += f"- {signature}\n"
            
            if len(methods) > 10:
                content += f"- ... and {len(methods) - 10} more methods\n"
            content += "\n"
        
        return content
    
    def _is_private_class(self, class_name: str) -> bool:
        """Determine if a class is a private implementation class that should be excluded."""
        class_simple_name = class_name.split('::')[-1]
        
        # Check against excluded patterns from config
        if self._matches_excluded_pattern(class_name):
            return True
        if self._matches_excluded_pattern(class_simple_name):
            return True
        
        # Filter out private implementation classes
        private_patterns = [
            'Impl_',     # Implementation classes ending with Impl_
            '_Impl',     # Implementation classes ending with _Impl
            '_Internal', # Internal classes
            '_impl',     # lowercase impl
            'impl_',     # lowercase impl prefix
        ]
        
        # Check if class name ends with or contains private patterns
        for pattern in private_patterns:
            if class_simple_name.endswith(pattern) or pattern in class_simple_name:
                return True
        
        # Filter out classes with leading underscores (typically private)
        if class_simple_name.startswith('_'):
            return True
            
        # Filter out classes ending with underscore (like Impl_)
        if class_simple_name.endswith('_'):
            return True
            
        return False
    
    def _should_document_class(self, class_name: str) -> bool:
        """Check if a class should be included in documentation."""
        # Only document classes that are in key_classes list
        key_classes = self.key_classes_config.get('key_classes', [])
        return class_name in key_classes
    
    def generate_docs(self, skip_cleanup=False):
        """Generate Markdown documentation files."""
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        
        # Clean previously generated files
        if not skip_cleanup:
            clean_generated_docs(OUTPUT_DIR)
        
        # Check generation mode
        if self.key_classes_config.get('generate_separate_files', False):
            # New mode: one file per class
            self._generate_separate_class_files()
        elif self.key_classes_config.get('generate_category_pages', False):
            self._generate_category_docs()
        else:
            # Legacy: Group classes by root namespace (only include key classes)
            namespace_groups = {}
            for class_name, class_info in self.classes.items():
                namespace = class_info['namespace']
                root_ns = namespace.split('::')[0] if namespace else 'global'
                
                if root_ns in self.target_namespaces and self._should_document_class(class_name):
                    if root_ns not in namespace_groups:
                        namespace_groups[root_ns] = []
                    namespace_groups[root_ns].append(class_info)
            
            # Generate documentation for each namespace
            for ns_name, classes in namespace_groups.items():
                self._generate_namespace_doc(ns_name, classes)
            
            # Generate legacy index files
            self._generate_index_rst(namespace_groups)
            self._generate_index_md(namespace_groups)
            self._generate_meta_file(namespace_groups)
        
        # Generate reference-level _meta.ts
        self._generate_reference_meta_file()
        
        print(f"📝 Generated C++ API documentation in {OUTPUT_DIR}")
    
    def _generate_separate_class_files(self):
        """Generate separate markdown files for each key class."""
        class_files_config = self.key_classes_config.get('class_files', {})
        key_classes = self.key_classes_config.get('key_classes', [])
        
        generated_files = []
        # Track classes that are included in other files
        included_classes = set()
        for class_name, file_config in class_files_config.items():
            for included in file_config.get('include_classes', []):
                included_classes.add(included)
        
        for class_name in key_classes:
            # Skip classes that are included in other files
            if class_name in included_classes:
                continue
                
            if class_name not in self.classes:
                print(f"⚠️ Class {class_name} not found in parsed classes")
                continue
            
            class_info = self.classes[class_name]
            file_config = class_files_config.get(class_name, {})
            
            # Determine filename
            simple_name = class_name.split('::')[-1]
            filename_base = file_config.get('filename', simple_name.lower())
            title = file_config.get('title', simple_name)
            
            # Collect additional classes to include in this file
            additional_classes = []
            for included_class in file_config.get('include_classes', []):
                if included_class in self.classes:
                    additional_classes.append(self.classes[included_class])
            
            # Generate the file
            self._generate_class_file(filename_base, title, class_info, additional_classes)
            generated_files.append({
                'filename': filename_base,
                'title': title,
                'class_name': class_name,
                'description': file_config.get('description', class_info.get('brief', ''))
            })
        
        # Generate index files
        self._generate_separate_index_rst(generated_files)
        self._generate_separate_index_md(generated_files)
        self._generate_separate_meta_file(generated_files)
    
    def _generate_class_file(self, filename_base: str, title: str, class_info: Dict[str, Any], additional_classes: list = None):
        """Generate a markdown file for a single class (optionally with additional related classes)."""
        filename = OUTPUT_DIR / f"{filename_base}.md"
        
        content = f"# {title}\n\n"
        content += f"**Full name:** `{class_info['name']}`\n\n"
        
        if class_info.get('brief'):
            content += f"{class_info['brief']}\n\n"
        
        # Add detailed docs using existing method
        content = self._add_detailed_class_docs(content, class_info)
        
        # Add additional related classes
        if additional_classes:
            for additional_class in additional_classes:
                additional_name = additional_class['name'].split('::')[-1]
                content += f"\n---\n\n## {additional_name}\n\n"
                content += f"**Full name:** `{additional_class['name']}`\n\n"
                
                if additional_class.get('brief'):
                    content += f"{additional_class['brief']}\n\n"
                
                content = self._add_detailed_class_docs(content, additional_class)
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"📄 Generated {filename}")
    
    def _generate_separate_index_rst(self, generated_files: list):
        """Generate index.rst for separate class files."""
        filename = OUTPUT_DIR / "index.rst"
        
        content = """C++ API Reference
=================

.. toctree::
   :maxdepth: 2
   :caption: C++ API

"""
        for file_info in generated_files:
            content += f"   {file_info['filename']}\n"
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"📄 Generated {filename}")
    
    def _generate_separate_index_md(self, generated_files: list):
        """Generate index.md for separate class files."""
        filename = OUTPUT_DIR / "index.md"
        
        content = """# C++ API Reference

The NeuG C++ API provides high-performance, low-level access to graph database functionality. Designed for performance-critical applications, embedded systems, and advanced graph algorithms.

## Overview

The C++ API offers powerful capabilities for:

- **Database Management**: Open, configure, and manage NeuG database instances
- **Query Execution**: Execute Cypher queries with parameterized inputs
- **Result Processing**: Iterate over query results with type-safe access

## Core Classes

"""
        for file_info in generated_files:
            content += f"- **[{file_info['title']}]({file_info['filename']})** - {file_info['description']}\n"
        
        content += """
## Quick Start

### Include Headers

```cpp
#include <neug/main/neug_db.h>
#include <neug/main/connection.h>
```

### Basic Usage

```cpp
#include <neug/main/neug_db.h>
#include <iostream>

int main() {
  // Create and open database
  neug::NeugDB db;
  db.Open("/path/to/graph", 4);  // 4 threads

  // Create connection and execute query
  auto conn = db.Connect();
  auto result = conn->Query("MATCH (n:Person) RETURN n.name LIMIT 10", "read");

  // Process results
  if (result.has_value()) {
    for (auto& record : result.value()) {
      std::cout << record.ToString() << std::endl;
    }
  }

  // Close database
  db.Close();
  return 0;
}
```

## Error Handling

```cpp
auto result = conn->Query("INVALID QUERY", "read");
if (!result.has_value()) {
  std::cerr << "Query failed: " << result.error().message() << std::endl;
}
```

## Thread Safety

- `NeugDB`: Thread-safe for all operations
- `Connection`: NOT thread-safe; use one connection per thread
- `QueryResult`: Thread-safe (read-only after creation)

"""
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"📄 Generated {filename}")
    
    def _generate_separate_meta_file(self, generated_files: list):
        """Generate _meta.ts for separate class files."""
        filename = OUTPUT_DIR / "_meta.ts"
        
        content = "export default {\n"
        content += '  "index": "C++ API Overview",\n'
        
        for file_info in generated_files:
            content += f'  "{file_info["filename"]}": "{file_info["title"]}",\n'
        
        content += "}\n"
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"📄 Generated {filename}")
    
    def _generate_category_docs(self):
        """Generate category-based documentation pages."""
        categories = self.key_classes_config.get('documentation_categories', {})
        
        for category_id, category_info in categories.items():
            self._generate_category_page(category_id, category_info)
        
        # Generate index files for categories
        self._generate_category_index_rst(categories)
        self._generate_category_index_md(categories)
        self._generate_category_meta_file(categories)
    
    def _generate_category_page(self, category_id: str, category_info: Dict[str, Any]):
        """Generate a single category documentation page."""
        filename = OUTPUT_DIR / f"{category_id}.md"
        
        title = category_info.get('title', category_id.title())
        description = category_info.get('description', '')
        class_names = category_info.get('classes', [])
        
        content = f"# {title}\n\n"
        
        if description:
            content += f"{description}\n\n"
        
        # Collect class info for this category
        category_classes = []
        for class_name in class_names:
            if class_name in self.classes:
                category_classes.append(self.classes[class_name])
            else:
                print(f"⚠️ Class {class_name} not found in parsed classes")
        
        if not category_classes:
            content += "*No classes found for this category.*\n"
        else:
            for class_info in category_classes:
                class_simple_name = class_info['name'].split('::')[-1]
                
                content += f"## {class_simple_name}\n\n"
                content += f"**Full name:** `{class_info['name']}`\n\n"
                
                if class_info.get('brief'):
                    content += f"{class_info['brief']}\n\n"
                
                # Add detailed documentation for all classes in categories
                content = self._add_detailed_class_docs(content, class_info)
                content += "\n---\n\n"
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"📄 Generated {filename}")
    
    def _generate_category_index_rst(self, categories: Dict[str, Any]):
        """Generate index.rst for category-based documentation."""
        filename = OUTPUT_DIR / "index.rst"
        
        content = """.. _cpp_api_reference:

C++ API Reference
==================

.. toctree::
   :maxdepth: 2

"""
        for category_id in categories.keys():
            content += f"   {category_id}\n"
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"📄 Generated {filename}")
    
    def _generate_category_index_md(self, categories: Dict[str, Any]):
        """Generate index.md with rich content for category-based docs."""
        filename = OUTPUT_DIR / "index.md"
        
        content = """# C++ API Reference

The NeuG C++ API provides high-performance, low-level access to graph database functionality. Designed for performance-critical applications, embedded systems, and advanced graph algorithms.

## Overview

The C++ API offers powerful capabilities for:

- **Database Management**: Open, configure, and manage NeuG database instances
- **Query Execution**: Execute Cypher queries with parameterized inputs
- **Direct Graph Access**: Low-level access to vertices, edges, and properties
- **Graph Traversal**: Efficient CSR-based edge iteration for custom algorithms

## Core Classes

"""
        
        for category_id, category_info in categories.items():
            title = category_info.get('title', category_id.title())
            class_names = category_info.get('classes', [])
            
            for class_name in class_names[:3]:  # Show top 3 classes per category
                simple_name = class_name.split('::')[-1]
                # Use simple relative link without anchor (like Python docs)
                content += f"- **[{simple_name}]({category_id})** - "
                # Add brief description based on class name
                if simple_name == "NeugDB":
                    content += "The main entry point for database operations\n"
                elif simple_name == "Connection":
                    content += "Execute Cypher queries against the database\n"
                elif simple_name == "QueryResult":
                    content += "Container for query results with iterator access\n"
                elif simple_name == "PropertyGraph":
                    content += "Low-level graph storage engine\n"
                elif simple_name == "Schema":
                    content += "Graph schema management (vertex/edge types)\n"
                elif simple_name == "CsrView":
                    content += "Efficient edge traversal in CSR format\n"
                else:
                    content += f"{simple_name} class\n"
        
        content += """
## Quick Start

### Include Headers

```cpp
#include <neug/main/neug_db.h>
#include <neug/main/connection.h>
```

### Basic Usage

```cpp
#include <neug/main/neug_db.h>
#include <iostream>

int main() {
    // Create and open database
    neug::NeugDB db;
    db.Open("/path/to/graph", 4);  // 4 threads

    // Create connection and execute query
    auto conn = db.Connect();
    auto result = conn->Query("MATCH (n:Person) RETURN n.name LIMIT 10", "read");

    // Process results
    if (result.has_value()) {
        while (result.value().hasNext()) {
            auto record = result.value().next();
            std::cout << record.ToString() << std::endl;
        }
    }

    // Close connection and database
    conn->Close();
    db.Close();
    return 0;
}
```

### Parameterized Queries

```cpp
// Safe parameter passing prevents injection
neug::execution::ParamsMap params;
params["min_age"] = neug::execution::Value(25);
params["city"] = neug::execution::Value("Beijing");

auto result = conn->Query(
    "MATCH (p:Person) WHERE p.age > $min_age AND p.city = $city RETURN p",
    "read",
    params
);
```

### Write Operations

```cpp
// Insert data
conn->Query("CREATE (p:Person {name: 'Alice', age: 30})", "insert");

// Update data
conn->Query("MATCH (p:Person {name: 'Alice'}) SET p.age = 31", "update");

// Delete data
conn->Query("MATCH (p:Person {name: 'Bob'}) DELETE p", "update");
```

## Advanced Usage

### Direct Graph Traversal

For performance-critical graph algorithms, use direct graph access:

```cpp
#include <neug/storages/graph/property_graph.h>
#include <neug/storages/csr/csr_view.h>

// Access the underlying property graph
const neug::PropertyGraph& graph = db.graph();
const neug::Schema& schema = graph.schema();

// Get label IDs
label_t person = schema.get_vertex_label_id("Person");
label_t knows = schema.get_edge_label_id("KNOWS");

// Create edge traversal view
neug::CsrView view = graph.GetGenericOutgoingGraphView(
    person, person, knows, neug::MAX_TIMESTAMP);

// Traverse neighbors of vertex v
vid_t v = 0;  // Internal vertex ID
neug::NbrList neighbors = view.get_edges(v);
for (auto it = neighbors.begin(); it != neighbors.end(); ++it) {
    vid_t neighbor_id = *it;
    // Process neighbor...
}
```

### Accessing Edge Properties

```cpp
// Get edge property accessor
neug::EdgeDataAccessor weight_accessor = graph.GetEdgeDataAccessor(
    person, person, knows, "weight");

// Access properties during traversal
for (auto it = neighbors.begin(); it != neighbors.end(); ++it) {
    double weight = weight_accessor.get_typed_data<double>(it);
    std::cout << "Edge weight: " << weight << std::endl;
}
```

### Accessing Vertex Properties

```cpp
// Get vertex property column
auto name_col = graph.GetVertexPropertyColumn(person, "name");

// Access property for a vertex
neug::Property name_prop = name_col->get_prop(vertex_id);
std::string_view name = name_prop.as_string_view();
```

## API Categories

"""
        
        for category_id, category_info in categories.items():
            title = category_info.get('title', category_id.title())
            description = category_info.get('description', '')
            class_names = category_info.get('classes', [])
            
            # Use simple link format like Python docs
            content += f"### [{title}]({category_id})\n\n"
            if description:
                content += f"{description}\n\n"
            
            for class_name in class_names:
                simple_name = class_name.split('::')[-1]
                content += f"- `{simple_name}`\n"
            content += "\n"
        
        content += """## Building

### Requirements

- **C++17 or later**: Modern C++ features for type safety and performance
- **CMake 3.15+**: Build system configuration
- **Dependencies**: See build documentation for complete list

### CMake Integration

```cmake
find_package(NeuG REQUIRED)
target_link_libraries(your_target NeuG::neug)
```

### Compile Example

```bash
g++ -std=c++17 -I/path/to/neug/include -L/path/to/neug/lib \\
    -lneug -o my_app my_app.cpp
```

## Error Handling

```cpp
auto result = conn->Query("INVALID QUERY", "read");
if (!result.has_value()) {
    std::cerr << "Query failed: " << result.error().message() << std::endl;
}
```

## Thread Safety

- `NeugDB`: Thread-safe for all operations
- `Connection`: NOT thread-safe; use one connection per thread
- `PropertyGraph`: Thread-safe for reads; writes require synchronization
- `CsrView`, `NbrList`, `NbrIterator`: Thread-safe (read-only)

"""
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"📄 Generated {filename}")
    
    def _generate_category_meta_file(self, categories: Dict[str, Any]):
        """Generate _meta.ts for category-based documentation."""
        filename = OUTPUT_DIR / "_meta.ts"
        
        content = 'export default {\n'
        content += '  "index": "C++ API Overview",\n'
        
        for category_id, category_info in categories.items():
            title = category_info.get('title', category_id.title())
            content += f'  "{category_id}": "{title}",\n'
        
        content += "};\n"
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"📄 Generated {filename}")
    
    def _generate_namespace_doc(self, namespace: str, classes: List[Dict[str, Any]]):
        """Generate documentation for a namespace."""
        filename = OUTPUT_DIR / f"{namespace}.md"
        
        content = f"""# Namespace {namespace}

{self.namespaces.get(namespace, {}).get('brief', f'The {namespace} namespace contains core functionality.')}

"""
        
        if self.namespaces.get(namespace, {}).get('detailed'):
            content += f"{self.namespaces[namespace]['detailed']}\n\n"
        
        if classes:
            content += f"## Classes and Structures\n\n"
            
            # Sort classes: key classes first, then alphabetically
            def sort_key(class_info):
                is_key = self._is_key_class(class_info['name'])
                return (not is_key, class_info['name'])  # False sorts before True
            
            for class_info in sorted(classes, key=sort_key):
                class_simple_name = class_info['name'].split('::')[-1]
                
                # Add key class indicator with proper hierarchy
                if self._is_key_class(class_info['name']):
                    content += f"## {class_simple_name} ⭐\n\n"
                    content += f"**Full name:** `{class_info['name']}` **[Key API Class]**\n\n"
                else:
                    content += f"## {class_simple_name}\n\n"
                    content += f"**Full name:** `{class_info['name']}`\n\n"
                
                if class_info['brief']:
                    content += f"{class_info['brief']}\n\n"
                
                # Add documentation based on class priority
                if self._is_key_class(class_info['name']):
                    # Full documentation for key classes
                    content = self._add_detailed_class_docs(content, class_info)
                else:
                    # Basic documentation for other classes  
                    content = self._add_basic_class_docs(content, class_info)
                
                # Add separator between classes
                content += "\n---\n\n"
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"📄 Generated {filename}")
    
    def _generate_index_rst(self, namespace_groups: Dict[str, List]):
        """Generate index.rst file for Sphinx toctree (simple structure)."""
        filename = OUTPUT_DIR / "index.rst"
        
        content = """.. _cpp_api_reference:

C++ API Reference
==================

.. toctree::
   :maxdepth: 2

"""
        
        # Add namespace toctree entries (with gs first)
        def namespace_sort_key(ns_name):
            return (0 if ns_name == 'gs' else 1, ns_name)
        
        for ns_name in sorted(namespace_groups.keys(), key=namespace_sort_key):
            content += f"   {ns_name}\n"
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"📄 Generated {filename}")
    
    def _generate_index_md(self, namespace_groups: Dict[str, List]):
        """Generate index.md file with rich content for Nextra."""
        filename = OUTPUT_DIR / "index.md"
        
        content = """# C++ API Reference

The NeuG C++ API provides low-level access to graph database functionality, designed for performance-critical applications and advanced graph operations.

## Key API Classes ⭐

The following classes are the primary entry points and most commonly used components:

"""
        
        # Add key classes overview
        all_key_classes = []
        for ns_name, classes in namespace_groups.items():
            for class_info in classes:
                if self._is_key_class(class_info['name']):
                    all_key_classes.append((ns_name, class_info))
        
        if all_key_classes:
            for ns_name, class_info in sorted(all_key_classes, key=lambda x: x[1]['name']):
                class_simple_name = class_info['name'].split('::')[-1]
                class_brief = class_info.get('brief', '').split('.')[0] if class_info.get('brief') else 'Key API class'
                content += f"- **[{class_simple_name}]({ns_name}#{class_simple_name.lower()})** - {class_brief}\n"
            content += "\n"

        content += """## Namespace Organization

The C++ API is organized into the following namespaces:

"""
        
        # Add namespace descriptions (with gs first)
        def namespace_sort_key(ns_name):
            return (0 if ns_name == 'gs' else 1, ns_name)
        
        for ns_name in sorted(namespace_groups.keys(), key=namespace_sort_key):
            classes = namespace_groups[ns_name]
            ns_brief = self.namespaces.get(ns_name, {}).get('brief', f'{ns_name} namespace')
            content += f"- **[{ns_name}]({ns_name})** - {ns_brief} ({len(classes)} classes)\n"
        
        content += """

### Namespace Categories

- **Core namespaces** (`gs`, `common`): Fundamental database operations and data structures
- **Query processing** (`algebra`, `cypher`, `physical`): Graph algorithms and query execution
- **Data management** (`results`, `schema`): Result handling and schema management  
- **Infrastructure** (`server`): Server and networking components

## Quick Start

### Include Headers

```cpp
#include <neug/neug.h>
```

### Basic Usage

```cpp
// Connect to database
gs::Database db("path/to/database");
auto session = db.connect();

// Execute query
auto result = session.execute("MATCH (n) RETURN n LIMIT 10");

// Process results
for (const auto& record : result) {
    // Handle each record
}
```

## Building

The C++ API requires:

- **C++17 or later**: Modern C++ features for type safety and performance
- **CMake 3.15+**: Build system configuration
- **Required dependencies**: See build documentation for complete list

### CMake Integration

```cmake
find_package(NeuG REQUIRED)
target_link_libraries(your_target NeuG::neug)
```

## Design Principles

The C++ API is designed with the following principles:

- **Performance**: Zero-cost abstractions and efficient memory usage
- **Type Safety**: Compile-time type checking for graph operations
- **Extensibility**: Plugin architecture for custom algorithms
- **Compatibility**: Standard C++ interfaces for easy integration

"""
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"📄 Generated {filename}")
    
    def _generate_meta_file(self, namespace_groups: Dict[str, List]):
        """Generate _meta.ts file for Nextra navigation."""
        filename = OUTPUT_DIR / "_meta.ts"
        
        content = 'export default {\n'
        content += '  "index": "C++ API Overview",\n'
        
        # Add namespace entries (with gs first)
        def namespace_sort_key(ns_name):
            return (0 if ns_name == 'gs' else 1, ns_name)
        
        # Define namespace descriptions to match your format
        namespace_descriptions = {
            'gs': 'Namespace gs',
            'server': 'Namespace server',
            'results': 'Namespace results',
            'schema': 'Namespace schema'
        }
        
        for ns_name in sorted(namespace_groups.keys(), key=namespace_sort_key):
            if ns_name in namespace_descriptions:
                content += f'  "{ns_name}": "{namespace_descriptions[ns_name]}",\n'
        
        content += "};\n"
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"📄 Generated {filename}")
    
    def _generate_reference_meta_file(self):
        """Generate _meta.ts file for reference directory."""
        reference_dir = OUTPUT_DIR.parent
        filename = reference_dir / "_meta.ts"
        
        content = """export default {
  cpp_api: "C++ API",
  python_api: "Python API",
  java_api: "Java API",
};
"""
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"📄 Generated reference {filename}")

def generate_docs():
    """Generate documentation with cleanup."""
    print("🔍 Starting C++ API documentation generation...")
    
    generator = CppAPIGenerator()
    
    # Parse Doxygen XML
    if not generator.parse_doxygen_xml():
        print("❌ Failed to parse Doxygen XML!")
        return False
    
    # Generate documentation
    generator.generate_docs(skip_cleanup=False)
    
    print("✅ C++ API documentation generation completed!")
    return True

def generate_docs_no_clean():
    """Generate documentation without cleanup."""
    print("🔍 Starting C++ API documentation generation (no cleanup)...")
    
    generator = CppAPIGenerator()
    
    # Parse Doxygen XML
    if not generator.parse_doxygen_xml():
        print("❌ Failed to parse Doxygen XML!")
        return False
    
    # Generate documentation
    generator.generate_docs(skip_cleanup=True)
    
    print("✅ C++ API documentation generation completed!")
    return True

def main():
    """Main function with command line argument support."""
    parser = argparse.ArgumentParser(description='Generate C++ API documentation from Doxygen XML')
    parser.add_argument('--clean-only', action='store_true',
                        help='Only clean previously generated files, do not generate new documentation')
    parser.add_argument('--no-clean', action='store_true',
                        help='Skip cleaning step, only generate new documentation')

    args = parser.parse_args()

    if args.clean_only:
        # Only perform cleanup
        if OUTPUT_DIR.exists():
            clean_generated_docs(OUTPUT_DIR)
        else:
            print(f"📁 Output directory {OUTPUT_DIR} does not exist")
        print("🎉 Cleanup completed!")
        return 0
    else:
        # Generate docs (with or without cleaning)
        if args.no_clean:
            success = generate_docs_no_clean()
        else:
            success = generate_docs()
        
        return 0 if success else 1

if __name__ == "__main__":
    import sys
    sys.exit(main())
