#!/usr/bin/env python3
"""
Generate Python API documentation using pydoc-markdown

This script generates Markdown documentation for NeuG Python API modules.
It automatically cleans previously generated files before creating new ones.

Usage:
    python generate_python_docs.py                # Generate docs (with cleanup)
    python generate_python_docs.py --clean-only   # Only clean generated files
    python generate_python_docs.py --no-clean     # Generate without cleanup

Generated files:
    - neug.database.md
    - neug.connection.md  
    - neug.session.md
    - neug.query_result.md

Note: Only files generated by this script are cleaned/removed.
      Manual files like index.md, index.rst are preserved.
"""

import os
import sys
import subprocess
import tempfile
import yaml
import argparse
import glob
import re
from pathlib import Path

def get_modules_from_config(config_file: Path) -> list:
    """Extract module list from pydoc-markdown config file."""
    with open(config_file, 'r') as f:
        config = yaml.safe_load(f)
    
    modules = config.get('loaders', [{}])[0].get('modules', [])
    return modules

def clean_generated_docs(output_dir: Path, scripts_dir: Path):
    """Remove only the files generated by this script based on config."""
    print("🧹 Cleaning previously generated documentation...")
    
    try:
        config_file = scripts_dir / 'pydoc-markdown.yml'
        modules = get_modules_from_config(config_file)
        
        # Generate expected filenames based on config
        # Extract the actual module name that pydoc-markdown uses for filename
        generated_files = []
        for module in modules:
            # pydoc-markdown uses the last part of the module name for filename
            module_basename = module.split('.')[-1]
            generated_files.append(f"{module_basename}.md")
        
        # Also include _meta.ts file
        generated_files.append("_meta.ts")
        
        print(f"📋 Expected generated files: {generated_files}")
        
        cleaned_count = 0
        for filename in generated_files:
            file_path = output_dir / filename
            if file_path.exists():
                file_path.unlink()
                print(f"  🗑️  Removed {filename}")
                cleaned_count += 1
            else:
                print(f"  ℹ️   {filename} not found (skipping)")
        
        print(f"✅ Cleanup completed! Removed {cleaned_count} files.")
        
    except Exception as e:
        print(f"⚠️  Warning: Could not read config file for cleanup: {e}")
        print("🔍 Falling back to pattern-based cleanup...")
        
        # Fallback: clean files matching the typical pattern
        pattern = "neug.*.md"
        matching_files = list(output_dir.glob(pattern))

        for file_path in matching_files:
            # Skip index files and other manually created files
            if file_path.name not in ['index.md', 'index.rst']:
                file_path.unlink()
                print(f"  🗑️  Removed {file_path.name}")
        
        # Also clean _meta.ts in fallback mode
        meta_file = output_dir / "_meta.ts"
        if meta_file.exists():
            meta_file.unlink()
            print(f"  🗑️  Removed _meta.ts")

        print(f"✅ Fallback cleanup completed!")

def generate_docs():
    """Generate documentation for all modules using pydoc-markdown."""
    # Script is now in source/_scripts/
    scripts_dir = Path(__file__).resolve().parent
    doc_dir = scripts_dir.parent.parent  # from source/_scripts/ -> source/ -> doc/
    output_dir = scripts_dir.parent / 'reference' / 'python_api'  # source/reference/python_api
    output_dir.mkdir(parents=True, exist_ok=True)

    # Clean previously generated files
    clean_generated_docs(output_dir, scripts_dir)

    print(f"📁 Scripts directory: {scripts_dir}")
    print(f"📁 Doc directory: {doc_dir}")
    print(f"📁 Output directory: {output_dir}")

    # Get modules from config
    config_file = scripts_dir / 'pydoc-markdown.yml'
    modules = get_modules_from_config(config_file)
    
    print(f"📋 Generating docs for {len(modules)} modules: {modules}")
    
    # Generate documentation for each module separately
    for module in modules:
        print(f"\n🔄 Processing module: {module}")
        _run_single_module_generation(scripts_dir, doc_dir, output_dir, module)
    
    # Generate _meta.ts for Python API
    _generate_python_meta_file(output_dir, modules)

def _run_single_module_generation(scripts_dir: Path, doc_dir: Path, output_dir: Path, module: str):
    """Generate documentation for a single module using pydoc-markdown."""
    # Add Python bind path to PYTHONPATH (from doc/ dir)
    python_bind_path = doc_dir.parent / 'tools' / 'python_bind'
    env = os.environ.copy()
    if 'PYTHONPATH' in env:
        env['PYTHONPATH'] = f"{python_bind_path}:{env['PYTHONPATH']}"
    else:
        env['PYTHONPATH'] = str(python_bind_path)

    # Also add to current Python path for validation
    sys.path.insert(0, str(python_bind_path))

    # Determine output filename
    module_basename = module.split('.')[-1]
    output_file = output_dir / f"{module_basename}.md"

    # Create config for this specific module
    config = {
        'loaders': [{
            'type': 'python',
            'search_path': [str(python_bind_path)],
            'modules': [module]
        }],
        'processors': [
            {
                'type': 'filter',
                'expression': '''not (
                    (name.startswith("_") and name != "__init__") or
                    name in ["logging", "os", "json", "requests", "adapters"] or
                    name.startswith("ERR_") or
                    name in ["logger", "cur_file_path", "cur_dir_path", "resource_dir", "readable", "OK", "Code"]
                )'''
            },
            {
                'type': 'smart'
            }
        ],
        'renderer': {
            'type': 'markdown'
        }
    }

    # Create temporary config file
    with tempfile.NamedTemporaryFile(mode='w', suffix='.yml', delete=False) as temp_config:
        yaml.dump(config, temp_config, default_flow_style=False)
        temp_config_path = temp_config.name

    cmd = ['pydoc-markdown', temp_config_path]

    try:
        result = subprocess.run(
            cmd,
            cwd=doc_dir,
            env=env,
            capture_output=True,
            text=True,
            check=True
        )
        
        # Write output directly to file with post-processing
        if result.stdout:
            # Post-process the content to fix formatting issues
            processed_content = _post_process_markdown(result.stdout)
            
            # For query_result module, we want to keep the underscore
            # pydoc-markdown might generate it as queryresult.md, so we need to check both
            potential_files = [
                output_dir / f"{module_basename}.md",
                output_dir / f"{''.join(module_basename.split('_'))}.md"  # Handle queryresult case
            ]
            
            # Find which file actually exists or use the intended one
            actual_output_file = output_file
            for potential_file in potential_files:
                if potential_file.exists() and potential_file != output_file:
                    # Rename to the correct name
                    potential_file.rename(output_file)
                    break
            
            with open(actual_output_file, 'w') as f:
                f.write(processed_content)
            
            word_count = len(processed_content.split())
            print(f"  ✅ Generated {actual_output_file.name} ({word_count} words)")
        else:
            print(f"  ⚠️  No output for {module}")
            
    except subprocess.CalledProcessError as e:
        print(f"  ❌ Failed to generate docs for {module}:")
        print(f"     Return code: {e.returncode}")
        if e.stderr:
            print(f"     stderr: {e.stderr}")
            
    finally:
        # Clean up temporary config file
        try:
            os.unlink(temp_config_path)
        except OSError:
            pass

def _post_process_markdown(content: str) -> str:
    """Post-process the generated markdown to fix formatting issues."""
    lines = content.split('\n')
    processed_lines = []
    
    in_code_block = False
    skip_next_lines = 0
    
    i = 0
    while i < len(lines):
        line = lines[i]
        
        # Skip lines if we're in a skip block
        if skip_next_lines > 0:
            skip_next_lines -= 1
            i += 1
            continue
        
        # Fix module title - add "Module" prefix
        if re.match(r'^# neug\.[a-zA-Z_\\]+$', line.strip()):
            module_name = line.strip()[2:]  # Remove "# "
            processed_lines.append(f"# Module {module_name}")
            i += 1
            continue
        
        # Skip empty sections (sections with only anchors and no content)
        if line.startswith('## ') and not line.endswith(' Objects'):
            # Look ahead to see if this section has any content
            section_name = line.strip()[3:]  # Remove "## "
            j = i + 1
            has_content = False
            
            # Check lines until next section or end
            while j < len(lines):
                next_line = lines[j]
                if next_line.startswith('#'):  # Next section
                    break
                # Consider it has content if it has non-empty, non-anchor lines
                if (next_line.strip() and 
                    not next_line.startswith('<a id=') and 
                    not next_line.strip().startswith('##')):
                    has_content = True
                    break
                j += 1
            
            # Skip this entire section if it has no content
            if not has_content:
                # Skip this section and all lines until next section or end
                i += 1  # Skip the heading line
                while i < len(lines):
                    if lines[i].startswith('#'):  # Found next section
                        break
                    i += 1
                continue
        
        # Fix Sphinx-style code blocks to standard markdown
        if line.strip().startswith('.. code:: python'):
            processed_lines.append('```python')
            in_code_block = True
            i += 1
            continue
        
        # End code block when we hit a non-indented line after .. code::
        if in_code_block and line and not line.startswith('    ') and not line.startswith('\t'):
            processed_lines.append('```')
            processed_lines.append('')
            in_code_block = False
        
        # Fix heading levels for Returns, Parameters, etc. - use item list formatting
        if re.match(r'^(Returns|Parameters|Raises|Notes?)$', line.strip()):
            section_type = line.strip()
            processed_lines.append(f"- **{section_type}:**")
            
            # Look ahead to convert the following content to sub-list format
            i += 1
            
            while i < len(lines):
                next_line = lines[i]
                
                # Stop if we hit another section, heading, anchor, or method
                if (next_line.startswith('#') or 
                    re.match(r'^(Returns|Parameters|Raises|Notes?)$', next_line.strip()) or
                    next_line.strip().startswith('```') or
                    next_line.strip().startswith('<a id=') or
                    (next_line.strip() == '' and i + 1 < len(lines) and 
                     (lines[i + 1].startswith('#') or lines[i + 1].strip().startswith('<a id=')))):
                    break
                
                # Skip separator lines
                if re.match(r'^-{3,}$', next_line.strip()):
                    i += 1
                    continue
                
                # Process content lines
                if next_line.strip():
                    # Check if this line looks like a parameter/return name (not indented description)
                    if not next_line.startswith('    ') and not next_line.startswith('\t'):
                        # Parse parameter/return format: "name : type" or just "type"
                        line_content = next_line.strip()
                        
                        if ' : ' in line_content:
                            # Format: "parameter_name : type"
                            param_name, param_type = line_content.split(' : ', 1)
                            processed_lines.append(f"  - `{param_name}` ({param_type})")
                        elif section_type in ['Returns', 'Raises'] and line_content:
                            # For returns/raises, often just the type
                            processed_lines.append(f"  - **{line_content}**")
                        else:
                            # Fallback
                            processed_lines.append(f"  - **{line_content}**")
                    else:
                        # This is a description line - add as indented text under the sub-list item
                        description = next_line.strip()
                        if description:
                            processed_lines.append(f"    {description}")
                else:
                    # Empty line - preserve it but only if we're not at section boundary
                    if i + 1 < len(lines) and not lines[i + 1].startswith('#') and not lines[i + 1].strip().startswith('<a id='):
                        processed_lines.append('')
                
                i += 1
            
            # Don't increment i again since we already processed ahead
            continue
        
        # Fix section separators (--- lines) 
        if line.strip() == '-------' or re.match(r'^-{3,}$', line.strip()):
            # Skip these separator lines
            i += 1
            continue
            
        # Fix overly deep heading nesting
        if line.startswith('####'):
            # Convert #### to ###
            processed_lines.append(line.replace('####', '###', 1))
            i += 1
            continue
            
        processed_lines.append(line)
        i += 1
    
    # Close any remaining code block
    if in_code_block:
        processed_lines.append('```')
    
    # Join and clean up multiple empty lines
    result = '\n'.join(processed_lines)
    result = re.sub(r'\n{3,}', '\n\n', result)  # Replace 3+ newlines with 2
    
    return result

def _generate_python_meta_file(output_dir: Path, modules: list):
    """Generate _meta.ts file for Python API directory."""
    filename = output_dir / "_meta.ts"
    
    # Map module names to friendly names
    module_names = {
        'neug.database': 'Main Database Interface',
        'neug.connection': 'Database Connection',
        'neug.session': 'Session Management',
        'neug.query_result': 'Query Execution Results'
    }
    
    content = 'export default {\n'
    content += '  "index": "Python API Overview",\n'
    
    for module in modules:
        # Get the filename that was generated
        module_basename = module.split('.')[-1]
        friendly_name = module_names.get(module, f'{module} module')
        content += f'  "{module_basename}": "{friendly_name}",\n'
    
    content += '};\n'
    
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"📄 Generated Python API {filename}")

def _run_pydoc_generation(scripts_dir: Path, doc_dir: Path, output_dir: Path):
    """Legacy function - kept for compatibility."""
    pass

def main():
    """Main function with command line argument support."""
    parser = argparse.ArgumentParser(description='Generate Python API documentation using pydoc-markdown')
    parser.add_argument('--clean-only', action='store_true', 
                       help='Only clean previously generated files, do not generate new documentation')
    parser.add_argument('--no-clean', action='store_true',
                       help='Skip cleaning step, only generate new documentation')
    
    args = parser.parse_args()
    
    if args.clean_only:
        # Only perform cleanup
        scripts_dir = Path(__file__).parent
        output_dir = scripts_dir.parent / 'reference' / 'python_api'
        if output_dir.exists():
            clean_generated_docs(output_dir, scripts_dir)
        else:
            print(f"📁 Output directory {output_dir} does not exist")
        print("🎉 Cleanup completed!")
    else:
        # Generate docs (with or without cleaning)
        if args.no_clean:
            generate_docs_no_clean()
        else:
            generate_docs()

def generate_docs_no_clean():
    """Generate documentation without cleaning first."""
    # Script is now in source/_scripts/
    scripts_dir = Path(__file__).resolve().parent
    doc_dir = scripts_dir.parent.parent  # from source/_scripts/ -> source/ -> doc/
    output_dir = scripts_dir.parent / 'reference' / 'python_api'  # source/reference/python_api
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"📁 Scripts directory: {scripts_dir}")
    print(f"📁 Doc directory: {doc_dir}")
    print(f"📁 Output directory: {output_dir}")

    # Get modules from config
    config_file = scripts_dir / 'pydoc-markdown.yml'
    modules = get_modules_from_config(config_file)
    
    print(f"📋 Generating docs for {len(modules)} modules: {modules}")
    
    # Generate documentation for each module separately
    for module in modules:
        print(f"\n🔄 Processing module: {module}")
        _run_single_module_generation(scripts_dir, doc_dir, output_dir, module)
    
    # Generate _meta.ts for Python API
    _generate_python_meta_file(output_dir, modules)

if __name__ == '__main__':
    main()
